on:
  push:
    branches:
      - master

name: Package Extension

jobs:
  package:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - run: npm ci

      - run: npx vsce package --out coder.vsix

      - uses: actions/upload-artifact@v2
        with:
          name: coder.vsix
          path: ./coder.vsix
