on:
  workflow_dispatch:
name: Publish Extension
jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
      - run: npm ci
      - run: npm install -g vsce
      - name: Login to vsce
        run: echo ${{ secrets.VS_MARKETPLACE_PAT }} | vsce login coder
      - run: vsce publish
